name: Release AAB generate

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  playstore_name: pl.slaszu.workbreak

  # secrets
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore-aab'
          encodedString: ${{ secrets.KEYSTORE_AAB }}

      - uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run gradle tests
        run: ./gradlew test

      - name: Build app bundleRelease
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease
        env:
          SIGNING_KEYSTORE_FILE: ${{ steps.decode_keystore.outputs.filePath }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload abb to artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.BRANCH_NAME }}
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/